CC=gcc
CFLAGS=-Wall -lpthread

EXE= \
	pthread_game \
	pthread_hello_world \
	pthread_evil_1 \
	pthread_evil_2 \
	pthread_exit \
	pthread_mutex \
	pthread_producer_consumer \
	normal_strtok \
	pthread_strtok \
	pthread_strtok_r \

all: ${EXE}

clean:
	rm -f ${EXE}
